spring:
  application:
    name: ${APP_NAME:blazebankapigateway}
  security:
    oauth2:
      client:
        provider:
          external:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${REALM_NAME:blazebank}
        registration:
          external:
            provider: external
            client-name: ${CLIENT_NAME:blazebank}
            client-id: ${CLIENT_ID:blazebank}
            scope:
              - openid
              - offline_access
              - profile
            authorization-grant-type: authorization_code
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie

logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

backend:
  cardServiceUri: ${CARD_SERVICE_URI:lb://blazebankcardservice/card}
  paymentServiceUri: ${PAYMENT_SERVICE_URI:lb://blazebankpaymentservice/payment}