spring:
  application:
    name: blazebankapigateway
  security:
    oauth2:
      client:
        provider:
          external:
            issuer-uri: ${KEYCLOAK_URL:http://127.0.0.1:8080}/realms/blazebank
        registration:
          external:
            provider: external
            client-name: blazebank
            client-id: blazebank
            scope:
              - openid
              - offline_access
              - profile
            authorization-grant-type: authorization_code
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie

logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true