spring:
  application:
    name: blazebankapigateway
  security:
    oauth2:
      client:
        provider:
          external:
            issuer-uri: ${KEYCLOAK_URL:http://127.0.0.1:8080}/realms/blazebank
        registration:
          external:
            provider: external
            client-name: blazebank
            client-id: blazebank
            scope:
              - openid
              - offline_access
              - profile
            authorization-grant-type: authorization_code
logging:
  level:
    org:
      springframework:
        web: DEBUG

frontend:
  url: ${FRONTEND_URL:http://127.0.0.1:3000}